delete from cart where Cart_ID=1 or Cart_ID=2 or Cart_ID=3;
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (1, 1, 1, 1);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (1, 1, 2, 2);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (1, 1, 3, 1);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (1, 2, 12, 3);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (1, 2, 13, 5);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (2, 1, 15, 4);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (1, 3, 11, 3);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (1, 3, 19, 2);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (2, 2, 5, 1);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (2, 2, 7, 2);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (3, 1, 6, 2);

insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (4, 1, 6, 1);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (4, 1, 18, 2);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (4, 1, 14, 6);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (4, 1, 10, 1);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (3, 2, 3, 1);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (3, 2, 1, 2);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (3, 2, 9, 3);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (3, 2, 17, 4);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (4, 2, 10, 1);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (4, 2, 6, 1);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (2, 3, 12, 1);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (2, 3, 11, 10);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (2, 3, 19, 9);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (2, 3, 1, 1);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (3, 3, 4, 2);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (3, 3, 8, 4);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (4, 3, 2, 2);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (4, 3, 9, 5);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (4, 3, 15,7);

insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (1, 5, 4, 1);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (1, 5, 1, 2);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (1, 5, 2, 3);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (1, 5, 9, 1);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (2, 5, 12, 1);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (2, 5, 11, 2);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (2, 5, 9, 3);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (3, 5, 16, 6);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (4, 5, 10, 2);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (4, 5, 6, 4);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (1, 6, 12, 1);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (1, 6, 11, 10);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (1, 6, 14, 1);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (1, 6, 20, 4);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (2, 6, 5, 3);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (2, 6, 3, 5);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (3, 6, 13, 4);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (3, 6, 11, 8);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (3, 6, 3,3);

insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (1, 4, 3, 5);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (1, 4, 2, 3);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (2, 4, 8, 8);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (2, 4, 6, 3);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (2, 4, 11, 2);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (2, 4, 17, 2);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (2, 4, 20, 3);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (3, 4, 18, 7);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (3, 4, 19, 4);
insert into CART (Cart_ID, User_ID, Product_ID, Quantity_Ordered) values (4, 4, 16, 3);