insert into Customer_LoginDetails (Username,Password,Customer_ID) values ('vpotten1'   , 'vefni5324'   ,1);
insert into Customer_LoginDetails (Username,Password,Customer_ID) values ('fgiordano1' , 'roQVVB8pgj'  ,2);
insert into Customer_LoginDetails (Username,Password,Customer_ID) values ('gsumption2' , '5AgszrP2D40' ,3);
insert into Customer_LoginDetails (Username,Password,Customer_ID) values ('gpeppett3'  , 'NHs8Ug6cMi0' ,4);
insert into Customer_LoginDetails (Username,Password,Customer_ID) values ('jribbens4'  , 'WMfXviF8ZV0k',5);
insert into Customer_LoginDetails (Username,Password,Customer_ID) values ('rcarmo5'    , 'od5HiW'      ,6);
insert into Customer_LoginDetails (Username,Password,Customer_ID) values ('rlutas6'    , 'TAgHrY4y7'   ,7);
insert into Customer_LoginDetails (Username,Password,Customer_ID) values ('dbluschke7', 'YcxhwRZ9'     ,8);
insert into Customer_LoginDetails (Username,Password,Customer_ID) values ('ysweynson8' , '5TIJFaOe'    ,9);
insert into Customer_LoginDetails (Username,Password,Customer_ID) values ('adimic9'    , 'MZTfXOLWU'   ,10);