insert into PRODUCTS (Product_ID, Category_ID, Name, Price, Quantity_Available, Seller_ID, Days_to_Arrive, Description) values (1, 1, 'External Supplier', 6721.89, 37, 11, 3, '');
insert into PRODUCTS (Product_ID, Category_ID, Name, Price, Quantity_Available, Seller_ID, Days_to_Arrive, Description) values (2, 6, 'Bread - Corn Muffaletta', 6125.82, 65, 20, 8, '');
insert into PRODUCTS (Product_ID, Category_ID, Name, Price, Quantity_Available, Seller_ID, Days_to_Arrive, Description) values (3, 10, 'Chicken Breast Halal', 6999.88, 93, 20, 10, '');
insert into PRODUCTS (Product_ID, Category_ID, Name, Price, Quantity_Available, Seller_ID, Days_to_Arrive, Description) values (4, 9, 'Dc Hikiage Hira Huba', 3786.98, 91, 3, 1, '');
insert into PRODUCTS (Product_ID, Category_ID, Name, Price, Quantity_Available, Seller_ID, Days_to_Arrive, Description) values (5, 2, 'Chef Hat 25cm', 5390.37, 16, 3, 1, '');
insert into PRODUCTS (Product_ID, Category_ID, Name, Price, Quantity_Available, Seller_ID, Days_to_Arrive, Description) values (6, 7, 'Cheese - Wine', 3568.37, 23, 15, 9, '');
insert into PRODUCTS (Product_ID, Category_ID, Name, Price, Quantity_Available, Seller_ID, Days_to_Arrive, Description) values (7, 5, 'Sachet', 5139.11, 22, 9, 3, '');
insert into PRODUCTS (Product_ID, Category_ID, Name, Price, Quantity_Available, Seller_ID, Days_to_Arrive, Description) values (8, 2, 'Jam - Marmalade, Orange', 7098.2, 85, 16, 3, '');
insert into PRODUCTS (Product_ID, Category_ID, Name, Price, Quantity_Available, Seller_ID, Days_to_Arrive, Description) values (9, 5, 'Chicken - Whole Fryers', 1320.45, 70, 7, 7, '');
insert into PRODUCTS (Product_ID, Category_ID, Name, Price, Quantity_Available, Seller_ID, Days_to_Arrive, Description) values (10, 10, 'Wine - Cotes Du Rhone Parallele', 7224.63, 47, 11, 5, '');
insert into PRODUCTS (Product_ID, Category_ID, Name, Price, Quantity_Available, Seller_ID, Days_to_Arrive, Description) values (11, 2, 'Gatorade - Fruit Punch', 2262.05, 53, 6, 10, '');
insert into PRODUCTS (Product_ID, Category_ID, Name, Price, Quantity_Available, Seller_ID, Days_to_Arrive, Description) values (12, 5, 'Juice - Orange, Concentrate', 470.97, 53, 11, 3, '');
insert into PRODUCTS (Product_ID, Category_ID, Name, Price, Quantity_Available, Seller_ID, Days_to_Arrive, Description) values (13, 7, 'Garlic - Elephant', 9724.75, 34, 10, 9, '');
insert into PRODUCTS (Product_ID, Category_ID, Name, Price, Quantity_Available, Seller_ID, Days_to_Arrive, Description) values (14, 5, 'Chocolate - Pistoles, White', 35.33, 1, 17, 10, '');
insert into PRODUCTS (Product_ID, Category_ID, Name, Price, Quantity_Available, Seller_ID, Days_to_Arrive, Description) values (15, 3, 'Pastry - Trippleberry Muffin - Mini', 3069.56, 43, 6, 6, '');
insert into PRODUCTS (Product_ID, Category_ID, Name, Price, Quantity_Available, Seller_ID, Days_to_Arrive, Description) values (16, 6, 'Kellogs All Bran Bars', 2704.39, 65, 17, 5, '');
insert into PRODUCTS (Product_ID, Category_ID, Name, Price, Quantity_Available, Seller_ID, Days_to_Arrive, Description) values (17, 10, 'Wine - Vidal Icewine Magnotta', 217.81, 96, 1, 9, '');
insert into PRODUCTS (Product_ID, Category_ID, Name, Price, Quantity_Available, Seller_ID, Days_to_Arrive, Description) values (18, 1, 'Lemon Balm - Fresh', 6621.0, 68, 8, 3, '');
insert into PRODUCTS (Product_ID, Category_ID, Name, Price, Quantity_Available, Seller_ID, Days_to_Arrive, Description) values (19, 9, 'Melon - Cantaloupe', 5784.59, 48, 17, 4, '');
insert into PRODUCTS (Product_ID, Category_ID, Name, Price, Quantity_Available, Seller_ID, Days_to_Arrive, Description) values (20, 4, 'Yokaline', 9353.85, 74, 14, 8, '')