insert into PRODUCTS (Product_ID, Category_ID, Name, Price, Quantity_Available, Seller_ID, Days_to_Arrive, Description, ImageSource) values (1, 1, 'External Supplier', 6721.89, 37, 1, 3, '','');
insert into PRODUCTS (Product_ID, Category_ID, Name, Price, Quantity_Available, Seller_ID, Days_to_Arrive, Description, ImageSource) values (2, 6, 'Bread - Corn Muffaletta', 6125.82, 65, 2, 8, '','');
insert into PRODUCTS (Product_ID, Category_ID, Name, Price, Quantity_Available, Seller_ID, Days_to_Arrive, Description, ImageSource) values (3, 10, 'Chicken Breast Halal', 6999.88, 93, 5, 10, '','');
insert into PRODUCTS (Product_ID, Category_ID, Name, Price, Quantity_Available, Seller_ID, Days_to_Arrive, Description, ImageSource) values (4, 9, 'Dc Hikiage Hira Huba', 3786.98, 91, 3, 1, '','');
insert into PRODUCTS (Product_ID, Category_ID, Name, Price, Quantity_Available, Seller_ID, Days_to_Arrive, Description, ImageSource) values (5, 2, 'Chef Hat 25cm', 5390.37, 16, 3, 1, '','');
insert into PRODUCTS (Product_ID, Category_ID, Name, Price, Quantity_Available, Seller_ID, Days_to_Arrive, Description, ImageSource) values (6, 7, 'Cheese - Wine', 3568.37, 23, 6, 9, '', '');
insert into PRODUCTS (Product_ID, Category_ID, Name, Price, Quantity_Available, Seller_ID, Days_to_Arrive, Description, ImageSource) values (7, 5, 'Sachet', 5139.11, 22, 9, 3, '','');
insert into PRODUCTS (Product_ID, Category_ID, Name, Price, Quantity_Available, Seller_ID, Days_to_Arrive, Description, ImageSource) values (8, 2, 'Jam - Marmalade, Orange', 7098.2, 85, 7, 3, '','');
insert into PRODUCTS (Product_ID, Category_ID, Name, Price, Quantity_Available, Seller_ID, Days_to_Arrive, Description, ImageSource) values (9, 5, 'Chicken - Whole Fryers', 1320.45, 70, 8, 7, '','');
insert into PRODUCTS (Product_ID, Category_ID, Name, Price, Quantity_Available, Seller_ID, Days_to_Arrive, Description, ImageSource) values (10, 10, 'Wine - Cotes Du Rhone Parallele', 7224.63, 47, 4, 5, '','');
