insert into SELLER (Seller_ID, Name, Location, Contact_No, Email_Id) values (1, 'Terri Chace', '436 Mcguire Trail', '770-674-5971', 'tchace0@acquirethisname.com');
insert into SELLER (Seller_ID, Name, Location, Contact_No, Email_Id) values (2, 'Luisa Ritter', '07 Gale Pass', '223-552-2461', 'lritter1@storify.com');
insert into SELLER (Seller_ID, Name, Location, Contact_No, Email_Id) values (3, 'Laura Blankhorn', '969 Hoard Way', '872-478-3537', 'lblankhorn2@hubpages.com');
insert into SELLER (Seller_ID, Name, Location, Contact_No, Email_Id) values (4, 'Neal Stennett', '3855 Katie Road', '239-280-9330', 'nstennett3@wordpress.com');
insert into SELLER (Seller_ID, Name, Location, Contact_No, Email_Id) values (5, 'Rinaldo Tilford', '94443 Johnson Pass', '616-487-2934', 'rtilford4@hhs.gov');
insert into SELLER (Seller_ID, Name, Location, Contact_No, Email_Id) values (6, 'Noami Westcot', '6 Carioca Center', '789-845-9143', 'nwestcot5@people.com.cn');
insert into SELLER (Seller_ID, Name, Location, Contact_No, Email_Id) values (7, 'Valery Lambarth', '971 Crest Line Lane', '886-555-9841', 'vlambarth6@wikipedia.org');
insert into SELLER (Seller_ID, Name, Location, Contact_No, Email_Id) values (8, 'Nollie Groome', '94 Briar Crest Plaza', '721-230-7595', 'ngroome7@webmd.com');
insert into SELLER (Seller_ID, Name, Location, Contact_No, Email_Id) values (9, 'Gwenora Blabie', '65728 Westerfield Circle', '578-396-5883', 'gblabie8@netvibes.com');
insert into SELLER (Seller_ID, Name, Location, Contact_No, Email_Id) values (10, 'Lisha Hasslocher', '464 Summer Ridge Road', '642-997-2642', 'lhasslocher9@engadget.com');
insert into SELLER (Seller_ID, Name, Location, Contact_No, Email_Id) values (11, 'Mollie Steutly', '6 Talmadge Lane', '314-620-8654', 'msteutlya@nps.gov');
insert into SELLER (Seller_ID, Name, Location, Contact_No, Email_Id) values (12, 'Merry Macallam', '83823 Corscot Court', '336-189-1100', 'mmacallamb@reuters.com');
insert into SELLER (Seller_ID, Name, Location, Contact_No, Email_Id) values (13, 'Nilson Margaret', '4602 Fulton Road', '785-269-0599', 'nmargaretc@addtoany.com');
insert into SELLER (Seller_ID, Name, Location, Contact_No, Email_Id) values (14, 'Leon Fennick', '374 Kenwood Lane', '362-762-9042', 'lfennickd@hao123.com');
insert into SELLER (Seller_ID, Name, Location, Contact_No, Email_Id) values (15, 'Derby Crowch', '00 Crowley Terrace', '796-303-2510', 'dcrowche@nationalgeographic.com');
insert into SELLER (Seller_ID, Name, Location, Contact_No, Email_Id) values (16, 'Kipp McJerrow', '0 Oneill Center', '235-561-2373', 'kmcjerrowf@quantcast.com');
insert into SELLER (Seller_ID, Name, Location, Contact_No, Email_Id) values (17, 'Roland Emney', '7 Mcbride Lane', '494-411-7930', 'remneyg@google.com.au');
insert into SELLER (Seller_ID, Name, Location, Contact_No, Email_Id) values (18, 'Whitney Boughton', '78 Lawn Center', '739-100-3056', 'wboughtonh@sitemeter.com');
insert into SELLER (Seller_ID, Name, Location, Contact_No, Email_Id) values (19, 'Reid Bragginton', '27638 Dawn Hill', '575-845-7891', 'rbraggintoni@xing.com');
insert into SELLER (Seller_ID, Name, Location, Contact_No, Email_Id) values (20, 'Granthem Dinnington', '38143 Golden Leaf Park', '292-896-8447', 'gdinningtonj@opensource.org');